lab_1/urls.py
from django.urls import path
from .views import index, friend_list

urlpatterns = [
    path('', index, name='index'),
    # TODO Add friends path using friend_list Views
    path('friends', friend_list, name='friend_list')
]

lab_2/urls.py
from django.urls import path
from .views import index, json, xml

urlpatterns = [
    path('', index, name='index'),
    path('json', json, name='json'),
    path('xml', xml, name='xml')
]

lab_3/urls.py
from django.urls import path
from .views import index,add_friend

urlpatterns = [
    path('', index, name='index'),
    path('add', add_friend, name='add')
]
    

lab_4/urls.py
from django.urls import path
from .views import index,note_list,add_note

urlpatterns = [
    path('', index, name='index'),
    path('note-list', note_list, name='notes_list'),
    path('add-note', add_note, name='add_note')
]

praktikum/urls.py
from django.urls import path, re_path
from django.contrib import admin
from django.urls.conf import include
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
from lab_1.views import index as index_lab1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-1/', include('lab_1.urls')),
    path('lab-2/', include('lab_2.urls')),
    path('lab-3/', include('lab_3.urls')),
    path('lab-4/', include('lab_4.urls')),
    re_path(r'^$', index_lab1, name='index')
]

lab_1/models.py
from django.db import models

# TODO Create Friend model that contains name, npm, and DOB (date of birth) here


class Friend(models.Model):
    name = models.CharField(max_length=30)
    # TODO Implement missing attributes in Friend model
    npm = models.IntegerField()
    dob = models.DateField()

lab_2/models.py
from django.db import models

# Create your models here.
class Note(models.Model):
    to = models.CharField(max_length=30)
    from_sender  = models.CharField(max_length=30)
    title = models.CharField(max_length=50)
    message =  models.CharField(max_length=250)

lab_3/models.py
from django.db import models
from lab_1.models import Friend
# Create your models here.

lab_4/models.py
from django.db import models
from lab_2.models import Note
# Create your models here.

lab_3/forms.py
from django.forms import widgets
from lab_1.models import Friend
from django import forms

#widget datepicker
class DateInput(forms.DateInput):
    input_type = 'date'

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = "__all__"
        widgets = {
            'dob' : DateInput()
        }

lab_4/forms.py
from lab_4.models import Note
from django import forms

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = "__all__"

lab_1/views.py
from .models import Friend
from django.shortcuts import render
from datetime import datetime, date

mhs_name = 'Visianita Widyaningrum'  # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2002,12,19)  # TODO Implement this, format (Year, Month, Date)
npm = 2006596610  # TODO Implement this


def index(request):
    response = {'name': mhs_name,
                'age': calculate_age(birth_date.year),
                'npm': npm}
    return render(request, 'index_lab1.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0


def friend_list(request):
    friends = Friend.objects.all().values() # TODO Implement this
    response = {'friends': friends}
    return render(request, 'friend_list_lab1.html', response)

lab_2/views.py
from django.http.response import HttpResponse
from django.core import serializers
from django.shortcuts import render
from .models import Note

# Create your views here.
def index(request):
    response = { 'notes' : Note.objects.all()}
    return render(request, 'lab2.html', response)

def xml(request):
    data = serializers.serialize('xml', Note.objects.all())
    return HttpResponse(data, content_type="application/xml")

def json(request):
    data = serializers.serialize('json', Note.objects.all())
    return HttpResponse(data, content_type="application/json")

lab_3/views.py
from django.shortcuts import render
from django.http.response import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import Friend
from lab_3.forms import FriendForm

# Create your views here.
@login_required(login_url='/admin/login/')
def index(request):
    friends = Friend.objects.all().values() # TODO Implement this
    response = {'friends': friends}
    return render(request, 'friend_list_lab3.html', response)

@login_required(login_url='/admin/login/')
def add_friend(request):
    context ={}

    # create object of form
    form = FriendForm(request.POST or None, request.FILES or None)

    # check if form data is valid
    if form.is_valid():
        # save the form data to model
        form.save()
        if request.method == 'POST':
            return HttpResponseRedirect('/lab-3')
    
    context['form']= form
    return render(request, "lab3_form.html", context)

lab_4/views.py
from django.shortcuts import render
from django.http.response import HttpResponse, HttpResponseRedirect
from .models import Note
from lab_4.forms import NoteForm

# Create your views here.
def index(request):
    response = {'notes' : Note.objects.all()}
    return render(request, 'lab4_index.html', response)

def note_list(request):
    response = {'notes' : Note.objects.all()}
    return render(request, 'lab4_note_list.html', response)

def add_note(request):
    context ={}

    # create object of form
    form = NoteForm(request.POST or None, request.FILES or None)

    # check if form data is valid
    if form.is_valid():
        # save the form data to model
        form.save()
        if request.method == 'POST':
            return HttpResponseRedirect('/lab-4')
    
    context['form']= form
    return render(request, "lab4_form.html", context)

lab_1/templates/friend_list_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model -->
      <!-- EXAMPLE SECTION -->
      <body>
        {% if friends %} 
          {% for friend in friends %}
            {{ friend.name }}
            {{ friend.npm }}
            {{ friend.dob }}
          <br/>
          {% endfor %}
        {% endif %}
      </body>      
      <!-- END SECTION -->
    </table>
  </body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ name }}</title>
  </head>
  <body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
  </body>
</html>

lab_2/templates/lab2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Lab 2 PBP</title>
  </head>
  <style>
      .container {
        outline-style: solid;
        outline-width: 2px;
      }
  </style>
  <body>
    <h1>Notes</h1>
        {% if notes%}
            {% for note in notes %}
            <div class="container">
                <p>To: {{ note.to }}</p>
                <p>From: {{ note.from_sender }}</p>
                <p>Title: {{ note.title }}</p>
                <p>Message: {{ note.message }}</p>
            </div>
            {% endfor %}
        {% endif %}
  </body>
</html>

lab_3/templates/friend_list_lab3.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List - Lab 3 - PBP</title>
    <style>
      table, th, td {
        border: 1px solid rgb(90, 93, 95);
      }
      
      table {
        width: 100%;
      }
    </style>
  </head>
  <body>
    <h2>Friend List</h2>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
        {% if friends %} 
          {% for friend in friends %}
          <tr>
            <td>{{ friend.name }}</td>
            <td>{{ friend.npm }}</td>
            <td>{{ friend.dob }}</td>
          </tr>
          {% endfor %}
        {% endif %}      
    </table>
  </body>
</html>

lab_3/templates/lab3_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend Form - Lab 3 - PBP</title>
  </head>
  <body>
    <h2>Friend Form</h2>
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </div>
  </body>
</html>

lab_4/templates/lab4_form.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Notes Form - Lab 4 - PBP</title>
    <style>
        body {
            margin:0;
            padding:0;
            font-family: 'Montserrat', sans-serif;
            background: #243b55;
        }

        /* Navigation Bar */
        nav {
           background-color: rgba(0,0,0,.5); 
           position: sticky;
           padding: 4px;
        }

        nav a {
            color:white;
            text-decoration: solid;
            font-size: smaller;
        }

        nav li{
            display: inline;
            margin-right: 4px;
        }

        a:hover {
            color: lightsalmon;
            transition: 0.5s;
        }

        /* Form Field */
        form {
            position: absolute;
            top: 50%;
            left: 50%;
            width: 70%;
            padding: 20px;
            transform: translate(-50%, -50%);
            background: rgba(0,0,0,.5);
            box-sizing: border-box;
            box-shadow: 0 15px 25px rgba(0,0,0,.6);
            border-radius: 10px;
        }

        .user-box {
            width: 100%;
            padding: 5px 0;
            margin-bottom: 5px;
        }
        
        /* Labels */
        h2 {
            padding: 0;
            color: rgb(255, 254, 254);
            text-align: center;
        }

        label {
            display: block;
            padding: 2px;
            color: rgb(255, 254, 254);
            font-size: small;
        }

        label:first-of-type {
            margin-top: 0;
        }

        /* input */
        input {
            padding: .5em;
            border: solid 1 px;
            border-radius: 5px;
        }

        #id_to, #id_from_sender, #id_title {
            min-width: 40%;
        }

        #id_message {
            min-height: 8em;
            min-width: 90%;
            max-width: 95%;
            padding: .5em;
            border-radius: 5px;
        }

        /* button */
        #button {
            margin-top: 2em;
            padding: .5em;
            width: 10em;
            border-radius: 6px;
            background-color:white;
            color: #000000;
            font-weight: bold;
            font-size: 15px;
        }

    </style>
  </head>
  <body>
    <nav>
        <li> <a href="http://localhost:8000/lab-4/add-note"> Add </a> </li>
        <li> <a href="http://localhost:8000/lab-4/"> Table </a> </li>
        <li> <a href="http://localhost:8000/lab-4/note-list"> Cards </a> </li>
    </nav>
    <h2>Apa pesanmu?</h2>
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="user-box">
                <label for="id_to">Untuk:</label>
                {{ form.to }}
                <label for="id_from_sender">Dari:</label>
                {{ form.from_sender }}
                <label for="id_title">Tentang:</label>
                {{ form.title }}
                <label for="id_message">Pesan:</label>
                {{ form.message }}
                <br>
                <input type="submit" value="Submit" id="button">
            </div>
        </form>
    </div>
  </body>
</html>

lab_4/templates/lab4_index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Notes Table - Lab 4 - PBP</title>
    <style>
      * {
        margin: 0;
        padding: 0;
        outline: 0;
        font-family: 'Montserrat', sans-serif;
        background-color: #243b55;
      }

      h2 {
        margin-top: 20px;
        text-align: center;
        color: white;
        font-weight: bold;
      }

      /* Navigation Bar */
      nav {
          background-color: #142130; 
          position: sticky;
          padding: 4px;
      }

      nav a {
          color:white;
          text-decoration: solid;
          font-size: smaller;
          background-color: #142130; 
      }

      nav li{
          display: inline;
          margin-right: 4px;
          background-color: #142130; 
      }
    
      a:hover {
        color:lightsalmon;
        transition: 0.5s;
      }
      
      /* Table */
      .content-table {
        position: absolute;
        left: 15%;
        margin: 25px 0;
        align-items: center;
        font-size: 0.9em;
        width: 70%;
        min-width: 400px;
        box-shadow: 0 0 15px rgba(0,0,0,.5);
        border-radius: 10px;
        border: white;
        overflow: hidden;
      }

      .content-table thead tr {
        color: white;
        text-align: center;
        font-weight: bold;
        border: #dddddd;
      }

      .content-table th {
        padding: 12px 12px;
        background-color: #142130;
        border: #dddddd;
      }

      .content-table td {
        padding: 12px 12px;
        background-color: #dddddd;
        color: black;
      }

    </style>
  </head>
  <body>
    <nav>
      <li> <a href="http://localhost:8000/lab-4/add-note"> Add </a> </li>
      <li> <a href="http://localhost:8000/lab-4/"> Table </a> </li>
      <li> <a href="http://localhost:8000/lab-4/note-list"> Cards </a> </li>
    </nav>
    <h2>Kumpulan Pesan Untukmu</h2>
    <div class="container">
      <table class="content-table">
        <thead>
          <tr>
            <th>Dari</th>
            <th>Untuk</th>
            <th>Tentang</th>
            <th>Pesan</th>
          </tr> 
        </thead>
        <tbody>
          {% if notes %} 
            {% for note in notes %}
            <tr>
              <td>{{ note.to }}</td>
              <td>{{ note.from_sender }}</td>
              <td>{{ note.title }}</td>
              <td>{{ note.message }}</td>
            </tr>
            {% endfor %}
          {% endif %}  
        </tbody>
      </table>
    </div>
    
  </body>
</html>

lab_4/templates/lab4_note_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Notes Card - Lab 4 - PBP</title>
    <style>
        body {
            margin:0;
            padding:0;
            font-family: 'Montserrat', sans-serif;
            background: #243b55;
            box-sizing: border-box;
        }

        h2 {
          margin-top: 20px;
          text-align: center;
          color: white;
          font-weight: bold;
        }

        /* Navigation Bar */
        nav {
            background-color: #142130; 
            position: sticky;
            padding: 4px;
        }

        nav a {
            color:white;
            text-decoration: solid;
            font-size: smaller;
            background-color: #142130; 
        }

        nav li{
            display: inline;
            margin-right: 4px;
            background-color: #142130; 
        }

        a:hover {
          color: lightsalmon;
          transition: 0.5s;
        }

        /* Cards */
        .cards {
          display: flex;
          flex-wrap: wrap;
          justify-content: space-between;
        }

        .card {
          margin: 20px;
          padding: 20px;
          width: 500px;
          min-height: 50px;
          display: grid;
          border-radius: 10px;
          background: rgba(0,0,0,.5);
          box-shadow: 0px 6px 10px rgba(0, 0, 0, 0.25);
          transition: all 0.2s;
        }

        .card:hover {
          box-shadow: 0px 6px 10px rgba(0, 0, 0, 0.4);
          transform: scale(1.01);
        }

        .card p {
          color: #dddddd;
          margin: 3px;
          position: relative;
        }

        .card #card-title {
          font-weight: bold;
          font-size: larger;
        }

        @media (max-width: 1600px) {
          .cards {
            justify-content: center;
          }
        }
    </style>
  </head>
  <body>
    <nav>
      <li> <a href="http://localhost:8000/lab-4/add-note"> Add </a> </li>
      <li> <a href="http://localhost:8000/lab-4/"> Table </a> </li>
      <li> <a href="http://localhost:8000/lab-4/note-list"> Cards</a> </li>
    </nav>
    <h2> Kumpulan Pesan Untukmu</h2>
    <div class="cards">
      {% if notes%}
          {% for note in notes %}
          <div class="card">
              <p id="card-title">{{ note.title }}</p>
              <p class="card-text">Untuk: {{ note.to }}</p>
              <p class="card-text">Dari: {{ note.from_sender }}</p>
              <p class="card-text">Pesan:</p>
              <p class="card-text">{{ note.message }}</p>
          </div>
          {% endfor %}
      {% endif %}
    </div>
  </body>
</html>